import Button from './Button'
import '../styles/Keypad.css'

export default function Keypad({clearString, handleEquation}){

  return (
    <div className="keypad">

      <Button 
        type='dark'
        screen='xᵞ'
        display='^'
        value='^'
        handleEquation={handleEquation}
      />
      <Button 
        type='colored'
        screen={clearString}
        value='clear'
        handleEquation={handleEquation}
      />
      <Button 
        type='colored'
        screen='←'
        value='delete'
        handleEquation={handleEquation}
      />
      <Button 
        type='colored'
        screen='%'
        display='/100'
        value='/100'
        handleEquation={handleEquation}
      />
      <Button 
        type='colored'
        screen='÷'
        display='÷'
        value='/'
        handleEquation={handleEquation}
      />

      <Button 
        type='dark'
        screen='√'
        display='sqrt('
        value='sqrt('
        handleEquation={handleEquation}
      />
      <Button 
        type='neutral'
        screen='7'
        display='7'
        value='7'
        handleEquation={handleEquation}
      />
      <Button 
        type='neutral'
        screen='8'
        display='8'
        value='8'
        handleEquation={handleEquation}
      />
      <Button 
        type='neutral'
        screen='9'
        display='9'
        value='9'
        handleEquation={handleEquation}
      />
      <Button 
        type='colored'
        screen='×'
        display='×'
        value='*'
        handleEquation={handleEquation}
      />

      <Button 
        type='dark'
        screen='1/x'
        display='^(-1)'
        value='^(-1)'
        handleEquation={handleEquation}
      />
      <Button 
        type='neutral'
        screen='4'
        display='4'
        value='4'
        handleEquation={handleEquation}
      />
      <Button 
        type='neutral'
        screen='5'
        display='5'
        value='5'
        handleEquation={handleEquation}
      />
      <Button 
        type='neutral'
        screen='6'
        display='6'
        value='6'
        handleEquation={handleEquation}
      />
      <Button 
        type='colored'
        screen='-'
        display='-'
        value='-'
        handleEquation={handleEquation}
      />

      <Button 
        type='dark'
        screen='('
        display='('
        value='('
        handleEquation={handleEquation}
      />
      <Button 
        type='neutral'
        screen='1'
        display='1'
        value='1'
        handleEquation={handleEquation}
      />
      <Button 
        type='neutral'
        screen='2'
        display='2'
        value='2'
        handleEquation={handleEquation}
      />
      <Button 
        type='neutral'
        screen='3'
        display='3'
        value='3'
        handleEquation={handleEquation}
      />
      <Button 
        type='colored'
        screen='+'
        display='+'
        value='+'
        handleEquation={handleEquation}
      />

      <Button 
        type='dark'
        screen=')'
        display=')'
        value=')'
        handleEquation={handleEquation}
      />
      <Button 
        type='neutral'
        screen='0'
        display='0'
        value='0'
        handleEquation={handleEquation}
      />
      <Button 
        type='neutral'
        screen='.'
        display='.'
        value='.'
        handleEquation={handleEquation}
      />
      <Button 
        type='equal'
        screen='='
        display='='
        value='equal'
        handleEquation={handleEquation}
      />
    </div>
  )
}